name: deploy to lambda
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ls -lsa
      - run: zip -r ${{env.ZIP_FILENAME}} *.py
      - run: sudo apt-get install python3-setuptools
      - run: python3 -m pip install --user awscli
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload zip to s3
        run: aws s3 cp ${{env.ZIP_FILENAME}} s3://${{env.S3_DEPLOYMENT_BUCKET_NAME}}/${{env.ZIP_FILENAME}}
      - name: Upload code to Lambda from zip
        run: aws lambda update-function-code --function-name ${{env.MENU_LAMBDA_FUNCTION_NAME}} --zip-file fileb://${{env.ZIP_FILENAME}}
